<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.openmrs.maven.parents</groupId>
		<artifactId>maven-parent-openmrs-module</artifactId>
		<version>1.1.1</version>
	</parent>

	<groupId>org.openmrs.module</groupId>
	<artifactId>reportbuilder</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>Report Builder</name>
	<description>This module Exposes APIs to support the report builder frontend application</description>

	<url>https://wiki.openmrs.org/x/FQ4z</url>

	<scm>
		<connection>scm:git:git@github.com:openmrs/openmrs-module-report-builder.git</connection>
		<developerConnection>scm:git:git@github.com:openmrs/openmrs-module-report-builder.git</developerConnection>
		<url>https://github.com/openmrs/openmrs-module-report-builder/</url>
	</scm>

	<modules>
		<module>api</module>
		<module>omod</module>
	</modules>

	<distributionManagement>
		<repository>
			<id>openmrs-repo-modules</id>
			<name>OpenMRS Nexus Modules</name>
			<url>https://mavenrepo.openmrs.org/nexus/content/repositories/modules</url>
		</repository>
		<snapshotRepository>
			<id>openmrs-repo-snapshots</id>
			<name>OpenMRS Nexus Snapshots</name>
			<url>https://mavenrepo.openmrs.org/nexus/content/repositories/snapshots</url>
		</snapshotRepository>
	</distributionManagement>

	<dependencyManagement>
		<dependencies>
			<!-- Begin OpenMRS core -->
			<dependency>
				<groupId>org.openmrs.api</groupId>
				<artifactId>openmrs-api</artifactId>
				<version>${openmrsPlatformVersion}</version>
				<type>jar</type>
				<scope>provided</scope>
			</dependency>

			<dependency>
				<groupId>org.openmrs.web</groupId>
				<artifactId>openmrs-web</artifactId>
				<version>${openmrsPlatformVersion}</version>
				<type>jar</type>
				<scope>provided</scope>
			</dependency>

			<dependency>
				<groupId>org.openmrs.api</groupId>
				<artifactId>openmrs-api</artifactId>
				<version>${openmrsPlatformVersion}</version>
				<type>test-jar</type>
				<scope>test</scope>
			</dependency>

			<dependency>
				<groupId>org.openmrs.web</groupId>
				<artifactId>openmrs-web</artifactId>
				<version>${openmrsPlatformVersion}</version>
				<type>test-jar</type>
				<scope>test</scope>
			</dependency>

			<dependency>
				<groupId>org.openmrs.test</groupId>
				<artifactId>openmrs-test</artifactId>
				<version>${openmrsPlatformVersion}</version>
				<type>pom</type>
				<scope>test</scope>
			</dependency>
			<!-- End OpenMRS core -->

			<dependency>
				<groupId>org.openmrs.module</groupId>
				<artifactId>calculation-api</artifactId>
				<version>${calculationVersion}</version>
				<scope>provided</scope>
			</dependency>

			<dependency>
				<groupId>org.openmrs.module</groupId>
				<artifactId>reporting-api</artifactId>
				<version>${reportingVersion}</version>
				<scope>provided</scope>
			</dependency>

			<dependency>
				<groupId>org.openmrs.module</groupId>
				<artifactId>serialization.xstream-api</artifactId>
				<version>${serialization.xstreamVersion}</version>
				<scope>provided</scope>
			</dependency>

			<dependency>
				<groupId>org.openmrs.module</groupId>
				<artifactId>webservices.rest-omod-common</artifactId>
				<version>${webservices.restModuleVersion}</version>
				<scope>provided</scope>
			</dependency>

			<dependency>
				<groupId>org.openmrs.module</groupId>
				<artifactId>webservices.rest-omod-common</artifactId>
				<version>${webservices.restModuleVersion}</version>
				<scope>provided</scope>
				<type>test-jar</type>
			</dependency>

			<dependency>
				<groupId>javax.annotation</groupId>
				<artifactId>javax.annotation-api</artifactId>
				<version>${javaxAnnotationVersion}</version>
				<scope>provided</scope>
			</dependency>

			<dependency>
				<groupId>org.openmrs.module</groupId>
				<artifactId>reportingcompatibility-api</artifactId>
				<version>${reportingCompatibilityVersion}</version>
				<scope>provided</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<repositories>
		<repository>
			<id>openmrs-repo</id>
			<name>OpenMRS Nexus Repository</name>
			<url>https://mavenrepo.openmrs.org/public</url>
		</repository>
		<repository>
			<id>central</id>
			<name>Maven Repository Switchboard</name>
			<layout>default</layout>
			<url>https://repo1.maven.org/maven2</url>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<id>openmrs-repo</id>
			<name>OpenMRS Nexus Repository</name>
			<url>https://mavenrepo.openmrs.org/public</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>

	<build>
		<pluginManagement>
			<plugins>
				<!-- Spotless plugin -->
				<plugin>
					<groupId>com.diffplug.spotless</groupId>
					<artifactId>spotless-maven-plugin</artifactId>
					<version>2.27.2</version>
					<configuration>
						<java>
							<licenseHeader>
								<file>${project.basedir}/license-header.txt</file>
							</licenseHeader>
							<eclipse>
								<file>${project.basedir}/OpenMRSFormatter.xml</file>
							</eclipse>
							<removeUnusedImports />
							<importOrder>
								<order>javax,java</order>
							</importOrder>
						</java>
						<formats>
							<format>
								<includes>
									<include>**/*.xml</include>
								</includes>
								<licenseHeader>
									<file>${project.basedir}/license-header.txt</file>
									<delimiter>^(?!&lt;\?xml)</delimiter>
								</licenseHeader>
							</format>
						</formats>
					</configuration>
					<executions>
						<execution>
							<id>spotless-apply</id>
							<phase>validate</phase>
							<goals>
								<goal>apply</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

	<properties>
		<openmrsPlatformVersion>2.6.3</openmrsPlatformVersion>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

		<calculationVersion>1.1</calculationVersion>
		<luceneVersion>6.6.0</luceneVersion>
		<reportingVersion>1.25.0</reportingVersion>
		<serialization.xstreamVersion>0.2.10</serialization.xstreamVersion>
		<webservices.restModuleVersion>2.28.0</webservices.restModuleVersion>
		<reportingCompatibilityVersion>2.0.9</reportingCompatibilityVersion>
		<javaxAnnotationVersion>1.3.2</javaxAnnotationVersion>
	</properties>
</project>